name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Execute Gradle build
      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build  # This ensures the test job runs after the build job

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Execute Gradle build and run tests
      - name: Execute Gradle tests
        run: |
          chmod +x ./gradlew
          ./gradlew test

  docker_build:
    runs-on: ubuntu-latest
    needs: [build, test]  # This ensures the docker_build job runs after build and test jobs

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Execute Gradle build
      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Build Docker image using Docker Compose
      - name: Build Docker image
        run: docker-compose build
