name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Upgraded to v4, which supports Node.js 20

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Upgraded to v3 for Node.js 20 support

      - name: Build Docker image
        run: docker build -t sachiket/task-management-system .

      # Run the tests inside Docker container
      - name: Run tests
        run: docker run sachiket/task-management-system ./gradlew test --no-daemon
