name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker image
      - name: Build Docker image
        run: docker-compose build

      # Run tests using Docker Compose
      - name: Run tests
        run: docker-compose up test --abort-on-container-exit

      # Run application (optional, if you want to check if the app runs after the tests)
#      - name: Run application
#        run: docker-compose up -d app
