name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Execute Gradle build (optional, if needed in other jobs)
      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew

  build:
    runs-on: ubuntu-latest
    needs: setup  # This ensures the setup job runs before the build job

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Run the setup steps from the setup job
      - uses: ./.github/workflows/main.yml@setup

      # Execute Gradle build
      - name: Execute Gradle build
        run: |
          ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: setup  # This ensures the setup job runs before the test job

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Run the setup steps from the setup job
      - uses: ./.github/workflows/main.yml@setup

      # Execute Gradle tests
      - name: Execute Gradle tests
        run: |
          ./gradlew test

  docker-build-and-push:
    runs-on: ubuntu-latest
    environment: prod
    needs: [build, test]  # This ensures the setup job runs before the build-and-push job

    steps:
      # Step 1: Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Run the setup steps from the setup job
      - uses: ./.github/workflows/main.yml@setup

      # Step 2: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/task-management-app:latest .

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/task-management-app:latest

  deploy:
    runs-on: ubuntu-latest
    environment: prod
    needs: [build, test, docker-build-and-push]

    steps:
      - uses: actions/checkout@v4

      # Run the setup steps from the setup job
      - uses: ./.github/workflows/main.yml@setup

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/task-management-app:latest .

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: TaskManagementService
          environment_name: TaskManagementService-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-216989125905
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip