# .github/workflows/setup.yml

name: Setup Workflow

on: [workflow_call]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Execute Gradle build (optional, if needed in other jobs)
      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew